package ast

type Visitor interface {
	VisitSinglePartQueryEnter(query *SinglePartQuery) error
	VisitSinglePartQueryLeave(query *SinglePartQuery) error
	VisitReadingClauseEnter(clause []ReadingClause) error
	VisitReadingClauseLeave(clause []ReadingClause) error
	VisitUpdatingClauseEnter(clause []UpdatingClause) error
	VisitUpdatingClauseLeave(clause []UpdatingClause) error
	VisitCreateEnter(clause *CreateClause) error
	VisitCreateLeave(clause *CreateClause) error
	VisitMatchEnter(clause *MatchClause) error
	VisitMatchLeave(clause *MatchClause) error
	VisitPatternEnter(pattern *Pattern) error
	VisitPatternLeave(pattern *Pattern) error
	VisitPatternPartEnter(part *PatternPart) error
	VisitPatternPartLeave(part *PatternPart) error
	VisitPatternElementNestedEnter(part *PatternElementNested) error
	VisitPatternElementNestedLeave(part *PatternElementNested) error
	VisitPatternElementPatternEnter(part *PatternElementPattern) error
	VisitPatternElementPatternLeave(part *PatternElementPattern) error
	VisitProjectionEnter(projection *Projection) error
	VisitProjectionLeave(projection *Projection) error
	VisitSortOrderEnter(order *SortOrder) error
	VisitSortOrderLeave(order *SortOrder) error
	VisitProjectionItemsEnter(items *ProjectionItems) error
	VisitProjectionItemsLeave(items *ProjectionItems) error
	VisitProjectionItemEnter(item *ProjectionItem) error
	VisitProjectionItemLeave(item *ProjectionItem) error
	VisitSortItemEnter(item *SortItem) error
	VisitSortItemLeave(item *SortItem) error
	VisitOpExpr(expr *OpExpr) error
	VisitUnaryExprEnter(expr *UnaryExpr) error
	VisitUnaryExprLeave(expr *UnaryExpr) error
	VisitBinaryExprEnter(expr *BinaryExpr) error
	VisitBinaryExprLeave(expr *BinaryExpr) error
	VisitTernaryExprEnter(expr *TernaryExpr) error
	VisitTernaryExprLeave(expr *TernaryExpr) error
	VisitListExprEnter(expr *ListExpr) error
	VisitListExprLeave(expr *ListExpr) error
	VisitListComprehensionExprEnter(expr *ListComprehensionExpr) error
	VisitListComprehensionExprLeave(expr *ListComprehensionExpr) error
	VisitPropertyLabelsExprEnter(expr *PropertyLabelsExpr) error
	VisitPropertyLabelsExprLeave(expr *PropertyLabelsExpr) error
	VisitSymbolicNameSchemaNameEnter(name *SymbolicNameSchemaName) error
	VisitSymbolicNameSchemaNameLeave(name *SymbolicNameSchemaName) error
	VisitReservedWordSchemaName(name *ReservedWordSchemaName) error
	VisitSymbolicNameIdentifier(name *SymbolicNameIdentifier) error
	VisitSymbolicNameHexLetter(name *SymbolicNameHexLetter) error
	VisitReservedWord(word *ReservedWord) error
	VisitLabel(label *Label) error
	VisitPrimitiveLiteral(literal *PrimitiveLiteral) error
	VisitListLiteralEnter(literal *ListLiteral) error
	VisitListLiteralLeave(literal *ListLiteral) error
	VisitParameterEnter(param *Parameter) error
	VisitParameterLeave(param *Parameter) error
	VisitCaseExprEnter(expr *CaseExpr) error
	VisitCaseExprLeave(expr *CaseExpr) error
	VisitCaseAltNodeEnter(alt *CaseAltNode) error
	VisitCaseAltNodeLeave(alt *CaseAltNode) error
	VisitQuantifierExprEnter(quantifier *QuantifierExpr) error
	VisitQuantifierExprLeave(quantifier *QuantifierExpr) error
	VisitFilterExprEnter(filter *FilterExpr) error
	VisitFilterExprLeave(filter *FilterExpr) error
	VisitVariableExprEnter(expr *VariableExpr) error
	VisitVariableExprLeave(expr *VariableExpr) error
	VisitPatternComprehensionExprEnter(expr *PatternComprehensionExpr) error
	VisitPatternComprehensionExprLeave(expr *PatternComprehensionExpr) error
	VisitNodePatternEnter(pattern *NodePattern) error
	VisitNodePatternLeave(pattern *NodePattern) error
	VisitMapLiteralEnter(literal *MapLiteral) error
	VisitMapLiteralLeave(literal *MapLiteral) error
	VisitPropertyKeyNameEnter(name *PropertyKeyName) error
	VisitPropertyKeyNameLeave(name *PropertyKeyName) error
	VisitPropertiesEnter(props *Properties) error
	VisitPropertiesLeave(props *Properties) error
	VisitRelationshipsPatternEnter(pattern *RelationshipsPattern) error
	VisitRelationshipsPatternLeave(pattern *RelationshipsPattern) error
	VisitPatternElementChainEnter(chain *PatternElementChain) error
	VisitPatternElementChainLeave(chain *PatternElementChain) error
	VisitRelationshipPatternEnter(pattern *RelationshipPattern) error
	VisitRelationshipPatternLeave(pattern *RelationshipPattern) error
	VisitRelationshipDetailEnter(detail *RelationshipDetail) error
	VisitRelationshipDetailLeave(detail *RelationshipDetail) error
	VisitRangeLiteral(literal *RangeLiteral) error
	VisitFunctionInvocationEnter(fnc *FunctionInvocation) error
	VisitFunctionInvocationLeave(fnc *FunctionInvocation) error
	VisitSymbolicFunctionNameEnter(name *SymbolicFunctionName) error
	VisitSymbolicFunctionNameLeave(name *SymbolicFunctionName) error
	VisitListOperatorExprEnter(expr *ListOperatorExpr) error
	VisitListOperatorExprLeave(expr *ListOperatorExpr) error
	VisitExistsFunctionName(name *ExistsFunctionName) error
}
